@CyberpunkTcgVault.Api_HostAddress = http://localhost:5096

GET {{CyberpunkTcgVault.Api_HostAddress}}/api/cards
Accept: application/json

###

GET {{CyberpunkTcgVault.Api_HostAddress}}/api/cards/1
Accept: application/json

###
GET {{CyberpunkTcgVault.Api_HostAddress}}/api/cards/567
Accept: application/json